### ISSUE TITLE
Clean up helm files

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-iac#1]
* [ ] Pull variables from env file

```yaml
envFrom:
  - configMapRef:
    name: env
```

* [ ] Clean up unused environment variables
* [ ] Use helm templates for git tags and environment variables
